### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by smajda** [pythonkc/pythonkc.com#20]
Our VM is using Python 3. We need to make the app work with Python 3. Also: how do you get virtualenvs working in ansible with python3. Please. @lgw4 this is your fault. :)

**Comment by smajda** [comment]
So here's what we've got so far in ansible:

```
- apt: pkg="{{ item }}" state=latest
  with_items:
    - build_essential
    - python3
    - python3-dev
    - python3-pip
    - python3-software-properties
    - python3-virtualenv

- pip: 
    requirments: "{{ project_root }}/requirements/project.txt"
    virtualenv: "/virtualenvs/pythonkc"
```

We get `Failed to find required executable virtualenv`.

Related issue: Ansible itself does not support Python 3 yet
